### ISSUE TITLE
mybatis自带扫描器无法初始化所有的Provider

### ISSUE THREAD

**Issue by fbestcode** [mybatis-book/book#35]
原项目使用spring和tk.mybatis结合的时候没有问题。
但是另外一个项目未使用spring，直接使用mybatis自带的扫描器加载所有mapper。这时候，执行到mapper中的基类方法时，总是出现以下错误：
Caused by: java.lang.NoSuchMethodException: tk.mybatis.mapper.provider.base.BaseSelectProvider.<init>()
	at java.lang.Class.getConstructor0(Class.java:3082)
	at java.lang.Class.newInstance(Class.java:412)
	... 11 more
调试发现是因为无法初始化Provider造成的。
请问有解决的办法吗？

**Comment by abel533** [comment]
需要按照文档配置 tk 开头的扫描器。
看这里：https://github.com/abel533/Mapper/blob/master/wiki/mapper3/2.Integration.md#2-%E7%BA%AFspring%E9%85%8D%E7%BD%AE%E6%96%B9%E5%BC%8F
