### ISSUE TITLE
MyBatis从入门到精通  第一章的第一个demo 出现以下问题！！！请大佬不吝赐教

### ISSUE THREAD

**Issue by qjfan** [mybatis-book/book#85]
simple(第一章)  CountryMapperTest 一直找不到org.apache.ibatis包
pom.xml 中引用
<dependency>
	<groupId>org.apache.ibatis</groupId>
	<artifactId>ibatis-core</artifactId>
	<version>3.0</version>
</dependency>

JUnit Test 报以下错误 sqlSessionFactory=null   [toString() unavailable - no suspended threads]

org.apache.ibatis.exceptions.IbatisException: 
### Cause: org.apache.ibatis.builder.BuilderException: Error parsing SQL Mapper Configuration. Cause: java.lang.NullPointerException
	at org.apache.ibatis.exceptions.ExceptionFactory.wrapException(ExceptionFactory.java:8)
	at org.apache.ibatis.session.SqlSessionFactoryBuilder.build(SqlSessionFactoryBuilder.java:32)
	at org.apache.ibatis.session.SqlSessionFactoryBuilder.build(SqlSessionFactoryBuilder.java:15)
	at tk.mybatis.simple.mapper.CountryMapperTest.init(CountryMapperTest.java:23)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)

貌似是没有识别出mybatis-config.xml中数据库的配置

<environments default="development">
<environment id="development">
	<transactionManager type="JDBC">
		<property name="" value=""/>
	</transactionManager>
	<dataSource type="UNPOOLED">
		<property name="driver" value="com.mysql.jdbc.Driver"/>
		
		<property name="url" value="jdbc:mysql://localhost:3306/mybatis"/>
		<property name="username" value="root"/>
		<property name="password" value="1234"/>
	</dataSource>
</environment>
</environments>

**Comment by qjfan** [comment]
<environments default="development">
<environment id="development">
	<transactionManager type="JDBC">
		<property name="" value=""/>
	</transactionManager>
	<dataSource type="UNPOOLED">
		<property name="driver" value="com.mysql.jdbc.Driver"/>
		
		<property name="url" value="jdbc:mysql://localhost:3306/mybatis"/>
		<property name="username" value="root"/>
		<property name="password" value="1234"/>
	</dataSource>
</environment>
</environments>

**Comment by qjfan** [comment]
是mybatis的版本太低，和mysql 8.0不匹配，
<dependency>
	<groupId>org.mybatis</groupId>
	<artifactId>mybatis</artifactId>
	<version>3.5.6</version>
	
</dependency>

<dependency>
	<groupId>org.apache.ibatis</groupId>
	<artifactId>ibatis-core</artifactId>
	<version>3.0</version>
	
</dependency>
